apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcacct-get-pods
  namespace: podgetter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-get-pods
  namespace: podgetter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-get-pods
  namespace: podgetter
subjects:
- kind: ServiceAccount
  name: svcacct-get-pods
  namespace: podgetter
roleRef:
  kind: Role
  name: role-get-pods
  apiGroup: rbac.authorization.k8s.io