apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JEQ0NBVlFDQVFBd0p6RU1NQW9HQTFVRUF3d0RZbTlpTVJjd0ZRWURWUVFLREE1a1pYWXRjRzlrTFhKbApZV1JsY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3NwS2k4SkxWbjNCVkRFCmxXYTYwZkRlTVhqSDlsMzY0ZzNQbGpTVURLNEdmUmt3ZHFWdUwrcG1yRjdUSTM1M1FpcXVHb3FCK3dJKyszVUcKeXRmOUhmT2U1L1BQTUovTW9maW9PTHJ6Tm9YZjFUS0EvNDI2c3NHTW1UNUM5aGMrdDdqRDRtUWJvZURzL1FFagp5Y005ODhlT1p6NFNUVDN4MDRIMzlRQ3Y0c21DMGJZc1JINVpVNHVxdU1VcE9UZnZqMDVQYWg2T0dkMUtsQ2lUClo1bFRPTXk1WXdCRVVMNWVHd1ZJWHcrNHc0dHVERlVBNW1QUW1QM01FOW1UM0Y3SUpoL1NrNHF4eExEbnZCUVcKMTFWb3VBMkt1NFYvWGZuU1ZsanlzRldGdngrc1RQVGRDQW5aNTlYNWNMR0dUekdDeWRaa2MzR1hXN2NHeHg4NgpMMmtxTjljQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBbDhJZHdrT05LWTFTM0o4ZHh2L3pUCkwrRERVb1V2b2taTE00TGlsYW5jdjNtZ3o4aXJMejFMazRXLzFWSkdkQmpFeGJhTTcxamNnckwyOCs0NGhxMHkKT25KbjNOTUM4YWlVNHJMUGlQek96cFZadG0vQkVGa2I4YkdDVmE4cGhkQTVPaFRaeUtoUGxQWWY3OVR1VStPeQp3VHo1cGRTSVJydUdNY2x0WFpOVDh5SERrNHdvTEFoMmRXUXNNUGhCc2dmZXpuWnhOOGw1UEg5MXFGQ1FtWGpQCk9HK093UFpGeUxzNmpwTy8yeUdHdWRhOG5FZ1c4S1AydmxHMnpNbFRhOE1zTzJHZm9xL2I4ekhsR3BPSldvQ3IKYWQ0dXBOYVAwQWdRTkUreFI4R2VwanNCL1RLODgvUktTTEIrZldhWUp2YTJ3aUFydGFWN0J5cEh0SG9mRjhJZQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31556952
  usages:
    - client auth
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jill
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JqQ0NBVllDQVFBd0tURU5NQXNHQTFVRUF3d0VhbWxzYkRFWU1CWUdBMVVFQ2d3UGNISnZaQzF3YjJRdApjbVZoWkdWeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbXE1dEM5aFdzSnRWCkkrN3ZIdTVuRk5sdDdGWTJRSnRuamFFTWdJa2w2RDVqb2lhMWk3TkQvOVltemhHT2dDN3JjaTAyMnFmVTlvbFcKaU85bG9vMkZxczNMMWNWbloxTlBudERUc3NhQkpWY3J6VDc0VjFOd1JTeDZVY1pVSm9aNXJYZVZtUzZRNlpxdgpjUndiTTVvNDVjaU1lbG1sYlp6aHZzSUVuTE9SOWdZYWgzNmk3T0E3U0w2WFlteXBWVDVpZGVMbGFidnYva3pGCkVqZ2FaWldXcE1uci9EQ25uVEVpVjVJL0JsemMzN1NPZGE4L2c3M3Y2OEowQWFYQ3gwbEJBV2xrTkU2NVZONUwKWEU0cW5mWEFQLy9FUk54ZkFVbDFZK053N1V5RWdqME56OUlhc0xjbWgydG5pZ05yNXc3L2xFWmQ3L2xtVDQ0KwpRWjM5MzcxbUpRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEbCtjU2Z0WWI0cW5lQU5FYVZQCjVVNXlwQkxhaHgvRFVEcTNnUnp4NW5FMVJBU0w3Z1NoUUJPRGNxNEtiMWJyUDRyL1FQU2d6cU9pYm5pV2FnNUoKNmV3K0Z5MmM1NkdzNDlPQjJ3UjJZRnBuRlEwbkxQaTRIVmw2Mzk1ODVoaTh0Zy8yZVVSUzMxSTgrL2hTQUxaZwo4TURCdFJzOC9FQWVrdDBlRHFkT0ZpclJWUXpBMjRSVW9yT0lGWnNYbUNHUjhzNG9LU3FLMC93UWpJQkdmVEhTCmJpSTdFWGZrMU9qSzJCSkdyUlJPb2xYSWI0aytOaXhMdXR0TXpwOVh1S2l3UnV4SnNlU1VkRzNNelJ3RzJOeGIKM0VGRmU1anhoRXV4OE83STcxbWNleWF6NkxPaDNDZC84cTdqZlhuVzdISm1VUHdFQ2dCRXlrS3o5cWJJZEE3cgozMXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31556952
  usages:
    - client auth
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dave
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2NUQ0NBVmtDQVFBd0xERU5NQXNHQTFVRUF3d0VaR0YyWlRFYk1Ca0dBMVVFQ2d3U1kyeDFjM1JsY2kxdwpiMlF0Y21WaFpHVnlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBhTW1DWDdtCnFLUTlacWxVbjByY3N1UUdLMm1CblR2UzF5UU0wOXJHeUlweS9MVkJMQzVLSEQvN0puU1o5MmY4eFFmZ2Z6UEoKbDJwdCs2WGY0VGJuSzZYRXVxODNNNysxUko2QXNDc0hpckswK3g2MENGd3Y4NlJUdy9xWmpwZUEzRGJFajVOVgpNMW1lN2ZTMXJrbDJ6dnJ6Z2swTE9QaE1wNGJXS2VhN05ZMDR0NUZrZnF3b29acVFUalNmaU9SQjEyVm8wYTZ5CkhqY2FsbXJrRkY1RFFtQmRseXVDN2hGYXZIZ3hCRG40TU1RWkczNi9jYjdhVVBDVmdTK2RIK25pTEdzQk5QZ2sKWHI4b21MTmJNWXQ1WFRIbHlCZGxhaG1WQWhpa0w3MHRBbVdVOUZaTy85aGd1RGg3SVpndFFvMk4vQmwrbHgzdgpudnB5ME42ZG9ROURhUUlEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHNsQzBhVlNMa1dzZWxFCnZmTFJ2bFMrZHVya2pQV1VIS0VNdmF1Q1BxdEFsMGRTK0srUllBVWN3WXNJMnJkTUhSWG9HNHdZNW9JcFVHL2MKL2NBem8xcXU4MitMRHJqUWJwalYwL1UwUWpoWnZZN3p5cXdZWTAva0hMNW94Znl6VU9wZzRDK1dRT1pHbUVwUApiWUhPU1FPTGJMYmxaTVVZNWg5YmJMK205bG1DRGk0dkE4M2ZFR0R2WU9HTnI3MXM3WW9YY05zTndwV01FNVJKClVqa3pmYTM3aXEwVUlrbGg2SUdxOTFhYVRDUVhWK2paa054a0xEL1Q5bU5LZ1dsUlBnVnF2ejNOYm00NjVINEMKdDhKUmlrM1pHOS9xUnUxMythOW5ON01xb1V1dXV3a3NoTE1iTDY5bmNFR0doZENwaklxWDdYSFozREU2U0JFcgo1d3pNY0xNPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31556952
  usages:
    - client auth






