apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app.kubernetes.io/name: curl
spec:
  containers:
  - name: curl
    image: geekmungus/alpine-curl:1.0.4
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      requests:
        cpu: '200m'
        memory: '256Mi'
      limits:
        cpu: '500m'
        memory: '512Mi'
    