apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
    tier: frontend
spec:
  containers:
    - name: curl
      image: lmacademy/alpine-curl:1.0.0
      resources:
        requests:
          cpu: '250m'
          memory: '256Mi'
        limits:
          cpu: '500m'
          memory: '512Mi'