apiVersion: v1
kind: Pod
metadata:
  name: curl3
  namespace: dev
  labels:
    app: curl3
spec:
  containers:
    - name: curl3
      image: lmacademy/alpine-curl:1.0.0
      resources:
        requests:
          cpu: '250m'
          memory: '256Mi'
        limits:
          cpu: '500m'
          memory: '512Mi'