apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen
spec:
  containers:
  - name: traffic-gen
    image: geekmungus/traffic-gen:1.0.0
    args:
      - 'color-api-clusterip/api'
      - '0.5'
