# Deployment Definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  labels:
    app: nginx-custom
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
        - name: nginx-custom
          image: geekmungus/nginx-custom:v2.0.9
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 256m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 256Mi
          startupProbe: # Probe to check container has started successfully. Runs only at startup.
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe: # Probe to check application is working correctly. Runs periodically as per the "periodSeconds" value.
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe: # Probe to check container is ready to accept traffic, i.e. after loading files, warming caches etc. Can ensure container is accepting traffic after load spikes for example.
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
  labels:
    app: nginx-custom
spec: 
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true # Requires a redeploy to add or remove.
  selector:
    app: nginx-custom
  ports:
  - port: 80
    targetPort: 80