apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
    - name: color-backend
      image: geekmungus/color-api:1.1.0
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-api-service
  namespace: dev
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 80